### ISSUE TITLE
Dataset download 이슈

### ISSUE THREAD

**Issue by ZIZUN** [SKTBrain/KVQA#2]
진행중인 연구에 KVQA 데이터셋을 활용하려 하는데,
다운로드가 원활히 되질 않네요..
gdown(구글드라이브 다운로드 위한 pip 패키지)을 사용했을 때, 
`
      Access denied with the following error:
      Too many users have viewed or downloaded this file recently. Please
      try accessing the file again later. If the file you are trying to
      access is particularly large or is shared with many people, it may
      take up to 24 hours to be able to view or download the file. If you
      still can't access a file after 24 hours, contact your domain
      administrator. 
`

다음과 같은 에러와 함께 다운로드가 되지 않습니다.
크롬으로도 받으려고 했으나, 다운 도중 끊기네요.. 용량이 커서 그런가

가능하다면, 데이터셋을 분할해서 공유해주시거나,
다른 다운로드 방법을 제공해 주신다면 감사하겠습니다.

**Comment by jnhwkim** [comment]
안녕하세요? 브라우저를 통해 다운로드 받으시길 바라며 혹시 24시간 뒤에도 동일한 에러메시지가 나온다면 답글 남겨주시면 감사하겠습니다.

**Comment by ZIZUN** [comment]
답변 주셔서 감사드립니다.

internet explorer로 링크 접속시 아래와 같은 페이지가 나오며,
엣지 브라우저의 새창으로 전환되게 됩니다.

![image](https://user-images.githubusercontent.com/24732802/164227326-0653bcde-2a73-436c-b508-6ba8876ee359.png)

그래서 엣지 브라우저로 다운로드 하려했는데, 다음과 같이 에러가 나옵니다.

![image](https://user-images.githubusercontent.com/24732802/164229153-d0825bd7-386d-421b-ade0-511753f4cca5.png)

크롬 브라우저는 다운로드는 되지만, 시간이 24시간 정도 걸리며, 다운 도중 연결이 끊겼습니다. (3번 정도 시도했었습니다.)

**Comment by jnhwkim** [comment]
[Huggingface](https://huggingface.co/datasets/skt/KVQA)에서 다운로드 받으실 수 있습니다.

**Comment by ZIZUN** [comment]
@jnhwkim  업로드 해주셔서 감사합니다!
